### ISSUE TITLE
Collaboration

### ISSUE THREAD

**Issue by ghost** [letianzj/quanttrader#2]
Hi, I just found your repository and liked it a lot. It remembers me of my event trading system working in python and controlling MT5 in the background.

Just wanted to reach out and see if you would be interested in further investigating the trading quest. My focus is currently building trading processed where the pattern analysis is only the beginning (position sizing, hedging during high DD, pairs integration and integration of manual trading in case the software is lost).

Feel free to reach out if you are interested

**Comment by letianzj** [comment]
Thanks for letting me know, mojovski. I'm glad you like it.

The control panel is designed with strategy control in mind such as limit control or flat all positions for that strategy. It has a simple order ticket but would rather expect traders to manual trade with say TWS chart trader. I know MT5 has all these built-in so that you can do both auto and discretionary trades inside MT5.

Free feel to open a ticket/pull request or send me an email at letian dot zj at gmail dot com. I'll close this ticket as solved.
